title: ISESteroids
author: tobiaspsp
email: tobias.weltner@email.de
description: > # this means to ignore newlines until "baseurl:"
  ISESteroids - PowerShell Editing for Professionals

# social links
twitter_username: tobiaspsp
github_username:  tobiasweltner

show_excerpts: true # set to false to remove excerpts on the homepage
